### ISSUE TITLE
Paging is not necessary and ads should display in descending order based on the reward amount

### ISSUE THREAD

**Issue by shnartho** [shnartho/app-metasurfai#10]
Paging is not necessary, and advertisements should be displayed in descending order based on the reward amount, with the highest rewards appearing at the top.

**Comment by JemalSmb** [comment]
I can add filter option instead of pagination, and just scroll until there isn't anymore.

**Comment by shnartho** [comment]
If you click on the iphone ad using device laptop, the close option will go out of scope.
![image](https://github.com/user-attachments/assets/0078fd41-bd03-4bdb-bffe-ea9781268d9d)

**Comment by JemalSmb** [comment]
yeah just seen that, it is fixed in the new branch. need access to the vercel of this repo to see the preview. at the moment, I need to push to a private repo to see the changes live instead of a dev server

**Comment by shnartho** [comment]
What we want is a standard shape for horizontal and all verticals ads. so any ad image should be either a horizontal 16:9 shape or a vertical shape 9:16.

**Comment by JemalSmb** [comment]
issue fixed
