### ISSUE TITLE
Ads timer not working properly and Image loading

### ISSUE THREAD

**Issue by shnartho** [shnartho/app-metasurfai#16]
1. If you keep the ads timer on and go to another tab, the timer stop during the time, but if you come back the timer will count faster than usual.
2. Sometime frontend fails to load all images, use retry machanism to solve this issue.

**Comment by JemalSmb** [comment]
ok

**Comment by JemalSmb** [comment]
I am doing ui change branch. most likely will be fixed with the fist commit, I will try to send a pr request by tmrw night

**Comment by JemalSmb** [comment]
The feat/ui-design has possible permanent solution for the timer not functioning correctly. I will fix the image loading issue in the next branch
